### ISSUE TITLE
Three Typos on this page

### ISSUE THREAD

**Issue by rcarrasco123** [adamaviv/ic220-s19#10]
Ricky Carrasco

"For example, there is a print_string and a print_int system call, that combined can be used to print to the console "the _anser_ = 5""
Should correct to "the **answer** = 5"

Some other system calls you may need are read_int, which will read an entire line of input, including the newline, and convert it to an integer. _Charcters_ following the number are _ignoreed_.

This line should correct to
**Characters** following the number are **ignored**.

**Comment by rcarrasco123** [comment]
Sorry, I didn't specify which page- systemcalls-howto.md

**Comment by rcarrasco123** [comment]
I found two more on the same page

read_string reads up to and including _he_ newline,
**the**

and

print_char and read_char do as _the_ suggest.
**they**

**Comment by adamaviv** [comment]
To receive credit for these, you have to submit a pull request not an issue. See these instructions! 

https://github.com/adamaviv/ic220-s19/blob/master/rsc/pull_requests.md
