### ISSUE TITLE
Main Website: Logo

### ISSUE THREAD

**Issue by rococoscout** [adamaviv/ic220-s19#11]
Your main website looks kinda off because the logo in the right hand corner is cut off. 
I tried putting the picture to a 100% instead of 195 % in your css template, but it still looked to small.
So, I just found a better logo for the job.[https://tulsastem.org/wp-content/uploads/2018/01/usna-logo-300x150.jpg](url)

V/R
Jess Lonetti

**Comment by adamaviv** [comment]
I'm not sure what this about. What's the main website?

**Comment by rococoscout** [comment]
https://www.usna.edu/Users/cs/aviv/

**Comment by adamaviv** [comment]
Thanks for your help on this ... but it's not ic220 related. As such, I'm going to close this ticket.
